# import time
# from selenium import webdriver
# driver = webdriver.Chrome(executable_path='C:/chromedriver.exe')
# driver.maximize_window()
# driver.get("https://practice.automationtesting.in/")
# time.sleep(3)
# driver.execute_script("window.scrollBy(0, 600);")
# Selenium_Ruby = driver.find_element_by_css_selector("[title='Selenium Ruby'].attachment-shop_catalog")
# Selenium_Ruby.click()
# Reviews = driver.find_element_by_class_name("reviews_tab")
# Reviews.click()
# five_stars = driver.find_element_by_class_name("star-5")
# five_stars.click()
# message = driver.find_element_by_id("comment")
# message.send_keys("Nice book!")
# Name = driver.find_element_by_id("author")
# Name.send_keys("Dmitry")
# Name = driver.find_element_by_id("email")
# Name.send_keys("1111@mail.ru")
# Submit = driver.find_element_by_css_selector("#submit[name='submit']")
# Submit.click()